### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by blitzboah**
when i extracted zip file i got a file your-archive.html and data folder.

when i renamed data folder to twitter-archive and paste it in the root of project folder and ran it i got an error

### CODE REVIEW

**Comment by blitzboah** [comment]
err

**Comment by blitzboah** [comment]
if this seems correct you can merge, else i have misread or didnt understood instructions.

**Comment by sankalp1999** [comment]
what happened in your case is an anomaly (some other users have faced too)
the current README and assumptions are fine, closing this PR.

**Comment by blitzboah** [comment]
ok senpai

**Pull request closed without merging**
